### ISSUE TITLE
[Bug]vscode新版本没有上传指令

### ISSUE THREAD

**Issue by u-mie** [batu1579/hamibot-assistant#17]
**错误描述**
Version: 1.76.0-insider (user setup)
Commit: c7930ca55d072608625ba76c13b5f9baaf9a2136
Date: 2023-02-10T16:22:19.445Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.25295
Sandboxed: Yes
使用F1输入hamibot-assistant.uploadAndRunScript 显示无此指令

**Comment by batu1579** [comment]
抱歉现在才看到，Orz

如果插件启动正常的话，在控制台输入 Hamibot 应该就能找到对应的指令（我一般只打 `ha` 就能看到所有相关的指令了），指令的全名叫 `Hamibot Operation: 上传标记的脚本文件` 。

当然还有另一种可能，在非项目文件夹中插件所注册的指令并不会全部启动，只有全局设置相关的指令和新建项目指令可以使用，主要用来避免使用了项目相关的指令时插件却找不到项目配置的问题。如果是这个原因导致的话可以尝试用指令新建一个项目然后把你现在的代码复制过去，生成的项目会自动创建项目配置，而不用你去手动查找脚本 ID 之类的烦人东西。

如果没解决的话可以在下面告诉我，我这几天都会来这里看看（如果解决了也拜托和我说一下，之前有个hxd让我等了一个星期...QAQ）

希望可以帮到你

**Comment by u-mie** [comment]
![QQ截图20230215170328](https://user-images.githubusercontent.com/34982474/218982787-f0393527-1a20-486c-b104-6cc6fec9ea58.png)
我是直接命令新建一个项目，想测试下生成的脚本 在生成的js文件按F1 结果没有看到上传的指令

**Comment by batu1579** [comment]
创建以后应该会打开一个新的工作区里面放的是生成的项目文件，你看一下里面有没有叫hamibot.config.json的文件

**Comment by u-mie** [comment]
有的
{
    "fileMark": {
        "scriptFile": "src/index.js",
        "configFile": "src/config.json"
    },
    "name": "hello",
    "scriptId": "-----------------",
    "executeRobot": {
        "_id": "--------------",
        "name": "Bot01"
    }
}

**Comment by batu1579** [comment]
再重新打开以后可能等一段时间才会开始加载这个插件，为了不影响打开速度我设置的是vscode完全准备好后才可用。如果你装的插件比较多的话也许可以打开以后等一小段时间在打开控制台。

**Comment by u-mie** [comment]
不知道好像木有用，还是找不到上传指令

**Comment by batu1579** [comment]
嘶这问题我还真没遇到过，可以让我看看截图嘛完整的vscode

**Comment by u-mie** [comment]
好像找到问题了，VSCODE workspace有其他项目的话就不显示，把workspace清空重新建才可以显示上传

**Comment by batu1579** [comment]
哦哦确实，我用的是第一个workspace。不过不用重新建，只需要都关上然后重新打开那个项目文件夹就可以，插件会自己读取那个config.json文件。
