### ISSUE TITLE
getClip()函数不见了

### ISSUE THREAD

**Issue by week12** [batu1579/hamibot-assistant#19]
**错误描述**
清晰而简洁的描述一下遇到的 Bug 。

**错误复现**
产生 Bug 的代码或要复现 Bug 需要进行的操作（这有助于尽快定位问题）:
1. 打开 '...'
2. 点击 '....'
4. 会出现 '...' 错误

**行为预期**
清晰而简明的描述一下你期望进行此操作产生的结果。

**截图**
如果可以的话，添加截图来帮助解释您遇到的问题。

**环境信息（请填写以下信息）：**
 - 操作系统： [例如 Windows 11]
 - VS Code 版本： [例如 1.70.0]
 - 插件版本： [例如 v1.0.0]

**其他说明**
任何有关该问题的其他说明。

**Comment by batu1579** [comment]
抱歉今天才看到，我马上就处理。QAQ

不过这个问题其实是类型声明忘记写了，应该在 [hamibot-types](https://github.com/batu1579/hamibot-types) 仓库中提交 issue ，不过我已经帮你搞定咯~

大大可以在这里看到后续： [缺少 getClip 函数的声明](https://github.com/batu1579/hamibot-types/issues/6)

我就先把这个 issue 关上辣~

**Comment by week12** [comment]
是的，我从gitlog里面找到了原来的函数声明，但是很奇怪，在软件页面调用获取到的为空，我得launch回hamibot再调用getClip才可以正常获取值

**Comment by batu1579** [comment]
> 是的，我从gitlog里面找到了原来的函数声明，但是很奇怪，在软件页面调用获取到的为空，我得launch回hamibot再调用getClip才可以正常获取值

好像确实会有这问题，有时候我要获取截图权限也需要先打开 hamibot ，不然可能会看不到请求的那个页面。不过我头一次知道这个获取也需要回到hamibot的页面hhhh
