### ISSUE TITLE
[Question]如何标记上传多个js文件

### ISSUE THREAD

**Issue by chchlsh** [batu1579/hamibot-assistant#20]
在使用模块化开发时，如何将模块化文件和主文件同时标记上传？目前试了只能上传一个

**Comment by jecoy** [comment]
同问

**Comment by batu1579** [comment]
Hi~@chchlsh @jecoy 

抱歉这么久才回复QAQ

目前 hamibot 本身不支持使用多文件的脚本，可以配合 Webpack 或者 [hamibot-starter](https://github.com/batu1579/hamibot-starter) 模板在上传前将项目打包然后标记打包后的文件。

> 在新建项目时选择对应的模板即可

![image](https://github.com/batu1579/hamibot-assistant/assets/51915056/10a0c0a0-41be-4f17-a42c-6de49c481414)

**Comment by chchlsh** [comment]
@batu1579 好的，非常感谢！

**Comment by batu1579** [comment]
晚上好~@jecoy @chchlsh 

如果没有别的问题了的话我就要把这个 issue 关上啦，以后要是还有相关的问题，你们可以重新把它打开~

bye~
