### ISSUE TITLE
[Bug]通过远程模板创建项目提示Unexpected end of JSON input

### ISSUE THREAD

**Issue by aembre** [batu1579/hamibot-assistant#21]
**错误描述**
通过远程模板创建项目，选择完机器人后，提示Unexpected end of JSON input

**错误复现**
产生 Bug 的代码或要复现 Bug 需要进行的操作（这有助于尽快定位问题）:
1. 打开 '...'
2. 点击 '....'
4. 会出现 '...' 错误

**行为预期**
清晰而简明的描述一下你期望进行此操作产生的结果。

**截图**
![image](https://github.com/batu1579/hamibot-assistant/assets/20717361/c7f687d3-8d69-4cd1-b1fe-9e21c8596d89)

**环境信息（请填写以下信息）：**
 - 操作系统： Windows 11
 - VS Code 版本： 1.82.0
 - 插件版本：Unreleased

**其他说明**
任何有关该问题的其他说明。

**Comment by o2pcc** [comment]
这个问题有解决方法了吗

**Comment by batu1579** [comment]
我发了新的版本，修复了这个问题，可以重新尝试一下还会不会遇到相同的问题。

至少在我这里测试是修复了。
